### ISSUE TITLE
A full disk crashes after converting video to images

### ISSUE THREAD

**Issue by Avasam** [milankarman/auto-loadless#22]
After converting I got a warning message about possible dropped frames, then it silently crashed.

Here's the most relevant error from windows event viewer. (the rest are generic file write errors with no stacktrace)
```
Application: Unload.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Configuration.ConfigurationErrorsException: Failed to save settings: An error occurred loading a configuration file: There is not enough space on the disk. : 'C:\Users\Avasam\AppData\Local\milankarman\Unload_Url_rf0ft2rzmgfxnytdef4cfvvl2wq5nvrb\1.3.0.0\13fcqj4k.newcfg' (C:\Users\Avasam\AppData\Local\milankarman\Unload_Url_rf0ft2rzmgfxnytdef4cfvvl2wq5nvrb\1.3.0.0\user.config)
 ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: There is not enough space on the disk. : 'C:\Users\Avasam\AppData\Local\milankarman\Unload_Url_rf0ft2rzmgfxnytdef4cfvvl2wq5nvrb\1.3.0.0\13fcqj4k.newcfg' (C:\Users\Avasam\AppData\Local\milankarman\Unload_Url_rf0ft2rzmgfxnytdef4cfvvl2wq5nvrb\1.3.0.0\user.config)
 ---> System.IO.IOException: There is not enough space on the disk. : 'C:\Users\Avasam\AppData\Local\milankarman\Unload_Url_rf0ft2rzmgfxnytdef4cfvvl2wq5nvrb\1.3.0.0\13fcqj4k.newcfg'
   at System.IO.FileStream.WriteCore(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.Configuration.SaveAsImpl(String filename, ConfigurationSaveMode saveMode, Boolean forceSaveAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at unload.StartWindow.LoadProject(String framesDirectory) in C:\Users\Milan\repos\Unload\Unload\src\windows\StartWindow.xaml.cs:line 129
   at unload.StartWindow.<>c__DisplayClass7_0.<btnConvert_Click>g__onFinished|0() in C:\Users\Milan\repos\Unload\Unload\src\windows\StartWindow.xaml.cs:line 197
   at unload.ConvertWindow.<>c__DisplayClass13_0.<btnConvert_Click>b__3() in C:\Users\Milan\repos\Unload\Unload\src\windows\ConvertWindow.xaml.cs:line 223
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at unload.ConvertWindow.<>c__DisplayClass13_0.<<btnConvert_Click>b__1>d.MoveNext() in C:\Users\Milan\repos\Unload\Unload\src\windows\ConvertWindow.xaml.cs:line 218
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by milankarman** [comment]
Not sure how to handle this properly yet as I don't think I can reliably estimate how big a conversion will be be. But I'll look into it soon. At the very least I'd like to give a warning if it happens.

**Comment by Avasam** [comment]
> I don't think I can reliably estimate how big a conversion will be be

Me neither, but if you can just catch the raised `System.Configuration.ConfigurationErrorsException` exception. Showing a warning would be preferable over a silent crash (even if Unload still closes itself afterward).

I knew what the issue was here, but another user may not guess/realize their disk is full.
