### ISSUE TITLE
Application crashes when presented a file in a folder with a name containing %

### ISSUE THREAD

**Issue by Shigbeard** [milankarman/auto-loadless#24]
(Tested on Windows 10 Pro Version 21H1, against Unload Release 1.3.0)

When attempting to Load & Convert a file inside of a folder, if that folder contains the percent (%) symbol (thusly referred to as the problematic folder), the process will critically fail. When attempting this conversion, Unload will successfully read info from the video file and ask you to modify details before confirming to convert. Additionally, it will briefly show a progress bar as it attempts to convert. A conversion folder will be created within the problematic folder, containing an accurate conversion-info.json file as expected. Unload will then display an error message indicating that the expected frame count does not match the converted frame count, before closing completely.

Unexpectedly, an extensionless file is created in the same directory as Unload, bearing the same name as the problematic folder (barring the percent symbol and any following characters). Opening this file in a hex editor indicates this file appears to be something left over by ffmpeg, as the header contains the string `Lavc58.134.100`. Opening it in VLC reveals it is a video file with the first frame of the video file i attempted to convert. This issue occurs regardless of what file I choose to convert, as long as the file I choose to convert is in a problematic folder or in a subfolder of a problematic folder.

Likely, this is firmly an ffmpeg issue, as it's evident that Unload is able to handle the file path correctly when saving it's `conversion-info.json` file, but this left-over file uses the same eac3 encoding version that ffmpeg uses, implying that this file was created by ffmpeg. This is as far as my investigation has gotten me, as I'm unfamiliar with this project's code base nor the C# language itself. However, Unload may be able to detect a problematic file path and either abort the conversion attempt or attempt to further sanitize the file path string for ffmpeg.

Additionally, Unload.exe produced this .NET runtime error in the Windows Event Log.

```
Application: Unload.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: '1' cannot be greater than 0.
   at System.Math.ThrowMinMaxException[T](T min, T max)
   at unload.MainWindow.SetVideoFrame(Int32 frameIndex) in C:\Users\Milan\repos\Unload\Unload\src\windows\MainWindow.xaml.cs:line 111
   at unload.MainWindow..ctor(Project _project) in C:\Users\Milan\repos\Unload\Unload\src\windows\MainWindow.xaml.cs:line 95
   at unload.StartWindow.LoadProject(String framesDirectory) in C:\Users\Milan\repos\Unload\Unload\src\windows\StartWindow.xaml.cs:line 135
   at unload.StartWindow.<>c__DisplayClass7_0.<btnConvert_Click>g__onFinished|0() in C:\Users\Milan\repos\Unload\Unload\src\windows\StartWindow.xaml.cs:line 197
   at unload.ConvertWindow.<>c__DisplayClass13_0.<btnConvert_Click>b__3() in C:\Users\Milan\repos\Unload\Unload\src\windows\ConvertWindow.xaml.cs:line 223
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at unload.ConvertWindow.<>c__DisplayClass13_0.<<btnConvert_Click>b__1>d.MoveNext() in C:\Users\Milan\repos\Unload\Unload\src\windows\ConvertWindow.xaml.cs:line 218
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by milankarman** [comment]
Thanks for the detailed write up. I'll look into this soon.
